e3
chorbintime/developers-dungeon-smp pull request #5
Opened 2024-09-16 16:36 UTC by RedstoneWizard08

e #3

2024-09-16 16:37 UTC, RedstoneWizard08 commented
@Noaaan hi again
also @chorbintime can i have write access pls

2024-09-16 21:08 UTC, RedstoneWizard08 commented
@Noaaan i fixed it

2024-09-17 15:53 UTC, Noaaan requested changes
Good work. Have some comments

2024-09-17 15:53 UTC, Noaaan commented on mods/lmft.pw.toml
While it makes the most sense to have LMFT on only the server, I think there is a valid use-case to also download on the client, simply for debugging purposes. This is a server for devs, after all

2024-09-17 15:53 UTC, Noaaan commented on cf_only_maybe.txt
I'll take a look at this list and see what I can figure out

2024-09-17 15:53 UTC, Noaaan commented on CHANGELOG.md
Do we have to manually update this now...?

2024-09-17 16:05 UTC, Noaaan commented on cf_only_maybe.txt
Mods by someaddon are not available on Modrinth, or any other platform outside of CF. They also seem to be ARR. This includes: 
- loot-integrations
- client-crafting
- structure-essentials
- client-crafting
- chunk-sending
- biome-music
- fix-gpu-memory-leak
- smooth-chunk-save
- recipe-essentials-forge-fabric
- connectivity
- fast-async-world-save-forge-fabric

The other two are mods from MrCrayFish. They seem to previously have been posted on Modrinth, but are no longer available. Framework is under LGPL, so that should be fine. This also goes for his furniture mod, as stated in the license: https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished?tab=readme-ov-file#license

2024-09-21 22:56 UTC, Noaaan commented
> Mods by someaddon are not available on Modrinth, or any other platform outside of CF. They also seem to be ARR. This includes:
> 
> * loot-integrations
> * client-crafting
> * structure-essentials
> * client-crafting
> * chunk-sending
> * biome-music
> * fix-gpu-memory-leak
> * smooth-chunk-save
> * recipe-essentials-forge-fabric
> * connectivity
> * fast-async-world-save-forge-fabric
> 
> The other two are mods from MrCrayFish. They seem to previously have been posted on Modrinth, but are no longer available. Framework is under LGPL, so that should be fine. This also goes for his furniture mod, as stated in the license: https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished?tab=readme-ov-file#license

We should be able to resolve this before the initial modpack release

2024-09-21 22:56 UTC, merged